dnl
dnl This file has been automatically generated by np_simple_glue.awk
dnl
divert(0)
np_simple_normal_out(PA0,p1)
np_simple_normal_out(PA1,p2)
np_simple_normal_out(PA2,p3)
np_simple_normal_out(PA3,p4)
